Repository nextbpmcloud/playground, pull requests merged in 2020-10, with the labels that each got.

#5 Initial test script
  run-tests.sh
Labels: enhancement

#14 Upload code coverage report
  README.md
  run-tests.sh
Labels: tests

#15 Python badge in README
  README.md
Labels: documentation
